--
-- PostgreSQL database dump
--

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.1

-- Started on 2026-08-09 22:58:06 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 16386)
-- Name: migrated_data; Type: SCHEMA; Schema: -; Owner: besy
--

CREATE SCHEMA IF NOT EXISTS migrated_data;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 253 (class 1259 OID 16645)
-- Name: address; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.address (
    id integer NOT NULL,
    postal_code character varying(20),
    building_name character varying(255),
    building_number character varying(255),
    comment character varying(255),
    country character varying(255),
    county character varying(255),
    legacy_address_name character varying(255),
    legacy_supplier_name character varying(255),
    owner_type character varying(255) NOT NULL,
    street character varying(255),
    town character varying(255) NOT NULL,
    CONSTRAINT address_owner_type_check CHECK (((owner_type)::text = ANY (ARRAY[('Supplier'::character varying)::text, ('Person'::character varying)::text])))
);


--
-- TOC entry 254 (class 1259 OID 16654)
-- Name: address_id_seq; Type: SEQUENCE; Schema: migrated_data; Owner: besy
--

ALTER TABLE migrated_data.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME migrated_data.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 16655)
-- Name: approvals; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.approvals (
    flag_edv_permission boolean,
    flag_furniture_permission boolean,
    flag_furniture_room boolean,
    flag_investment_room boolean,
    flag_investment_structural_measures boolean,
    flag_media_permission boolean,
    order_id bigint NOT NULL
);


--
-- TOC entry 256 (class 1259 OID 16659)
-- Name: cost_center; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.cost_center (
    begin_date date,
    end_date date,
    id character varying(20) NOT NULL,
    comment character varying(255),
    name character varying(255) NOT NULL
);


--
-- TOC entry 257 (class 1259 OID 16666)
-- Name: currency; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.currency (
    code character varying(3) NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 258 (class 1259 OID 16671)
-- Name: customer_id; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.customer_id (
    supplier_id integer NOT NULL,
    comment character varying(255),
    customer_id character varying(255) NOT NULL
);


--
-- TOC entry 259 (class 1259 OID 16678)
-- Name: invoice; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.invoice (
    date date NOT NULL,
    price numeric(8,2) NOT NULL,
    created_date timestamp(6) with time zone NOT NULL,
    order_id bigint NOT NULL,
    paperless_id bigint,
    cost_center_id character varying(20) NOT NULL,
    comment character varying(255),
    id character varying(255) NOT NULL
);


--
-- TOC entry 260 (class 1259 OID 16689)
-- Name: item; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.item (
    item_id integer NOT NULL,
    migrated_to_insy boolean NOT NULL,
    price_per_unit numeric(10,2) NOT NULL,
    vat_value numeric(38,2),
    order_id bigint NOT NULL,
    quantity bigint DEFAULT 1 NOT NULL,
    quantity_unit character varying(45),
    article_id character varying(255),
    comment character varying(255) DEFAULT ''::character varying,
    preferred_list character varying(255),
    preferred_list_number character varying(255),
    vat_type character varying(255) DEFAULT 'netto'::character varying NOT NULL,
    name text NOT NULL,
    CONSTRAINT item_preferred_list_check CHECK (((preferred_list)::text = ANY (ARRAY[('RZ'::character varying)::text, ('TA'::character varying)::text]))),
    CONSTRAINT item_vat_type_check CHECK (((vat_type)::text = ANY (ARRAY[('netto'::character varying)::text, ('brutto'::character varying)::text])))
);


--
-- TOC entry 261 (class 1259 OID 16706)
-- Name: order; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data."order" (
    auto_index smallint,
    booking_year character varying(2),
    cashback_days smallint,
    cashback_percentage numeric(3,2),
    delivery_address_id integer,
    fixed_discount numeric(10,2) DEFAULT 0.00,
    flag_decision_cheapest_offer boolean DEFAULT false,
    flag_decision_contract_partner boolean DEFAULT false,
    flag_decision_most_economical_offer boolean DEFAULT false,
    flag_decision_other_reasons boolean DEFAULT false,
    flag_decision_preferred_supplier_list boolean DEFAULT false,
    flag_decision_sole_supplier boolean DEFAULT false,
    invoice_address_id integer,
    legacy_alias character varying(2),
    owner_user_id bigint,
    percentage_discount numeric(4,2) DEFAULT 0.00,
    quote_date date,
    quote_price numeric(10,2),
    supplier_id integer,
    created_date timestamp(6) without time zone NOT NULL,
    delivery_person_id bigint,
    id bigint NOT NULL,
    invoice_person_id bigint,
    last_updated_time timestamp(6) without time zone,
    queries_person_id bigint,
    dfg_key character varying(45),
    comment character varying(255) DEFAULT ''::character varying,
    content_description character varying(255) NOT NULL,
    currency_short character varying(255),
    customer_id character varying(255),
    primary_cost_center_id character varying(255),
    quote_number character varying(255),
    quote_sign character varying(255),
    secondary_cost_center_id character varying(255),
    status character varying(255) NOT NULL,
    comment_for_supplier text,
    decision_other_reasons_description text,
    CONSTRAINT order_status_check CHECK (((status)::text = ANY (ARRAY[('IN_PROGRESS'::character varying)::text, ('COMPLETED'::character varying)::text, ('APPROVALS_RECEIVED'::character varying)::text, ('DEKAN_PENDING'::character varying)::text, ('APPROVED'::character varying)::text, ('REJECTED'::character varying)::text, ('SENT'::character varying)::text, ('SETTLED'::character varying)::text, ('ARCHIVED'::character varying)::text, ('DELETED'::character varying)::text])))
);


--
-- TOC entry 262 (class 1259 OID 16725)
-- Name: order_id_seq; Type: SEQUENCE; Schema: migrated_data; Owner: besy
--

ALTER TABLE migrated_data."order" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME migrated_data.order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 16726)
-- Name: order_status_history; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.order_status_history (
    id bigint NOT NULL,
    order_id bigint,
    "timestamp" timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT order_status_history_status_check CHECK (((status)::text = ANY (ARRAY[('IN_PROGRESS'::character varying)::text, ('COMPLETED'::character varying)::text, ('APPROVALS_RECEIVED'::character varying)::text, ('DEKAN_PENDING'::character varying)::text, ('APPROVED'::character varying)::text, ('REJECTED'::character varying)::text, ('SENT'::character varying)::text, ('SETTLED'::character varying)::text, ('ARCHIVED'::character varying)::text, ('DELETED'::character varying)::text])))
);


--
-- TOC entry 264 (class 1259 OID 16733)
-- Name: order_status_history_id_seq; Type: SEQUENCE; Schema: migrated_data; Owner: besy
--

ALTER TABLE migrated_data.order_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME migrated_data.order_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 16734)
-- Name: person; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.person (
    address_id integer,
    id bigint NOT NULL,
    fax character varying(45),
    phone character varying(45),
    title character varying(45),
    comment character varying(255),
    email character varying(255),
    gender character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    CONSTRAINT person_gender_check CHECK (((gender)::text = ANY (ARRAY[('m'::character varying)::text, ('f'::character varying)::text, ('d'::character varying)::text])))
);


--
-- TOC entry 266 (class 1259 OID 16744)
-- Name: person_id_seq; Type: SEQUENCE; Schema: migrated_data; Owner: besy
--

ALTER TABLE migrated_data.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME migrated_data.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 16745)
-- Name: quotation; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.quotation (
    index smallint NOT NULL,
    price numeric(10,2) NOT NULL,
    quote_date date NOT NULL,
    order_id bigint NOT NULL,
    company_city character varying(255) NOT NULL,
    company_name character varying(255) NOT NULL
);


--
-- TOC entry 268 (class 1259 OID 16756)
-- Name: supplier; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.supplier (
    address_id integer,
    deactivated_date date,
    flag_preferred boolean DEFAULT false NOT NULL,
    id integer NOT NULL,
    vat_id character varying(20),
    email character varying(45),
    fax character varying(45),
    phone character varying(45),
    comment character varying(255),
    name character varying(255) NOT NULL,
    website character varying(255)
);


--
-- TOC entry 269 (class 1259 OID 16765)
-- Name: supplier_id_seq; Type: SEQUENCE; Schema: migrated_data; Owner: besy
--

ALTER TABLE migrated_data.supplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME migrated_data.supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 270 (class 1259 OID 16766)
-- Name: user; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data."user" (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    keycloak_uuid character varying(255),
    legacy_user_name character varying(255),
    name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL
);


--
-- TOC entry 271 (class 1259 OID 16775)
-- Name: user_id_seq; Type: SEQUENCE; Schema: migrated_data; Owner: besy
--

ALTER TABLE migrated_data."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME migrated_data.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 272 (class 1259 OID 16776)
-- Name: user_preferences; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.user_preferences (
    id integer NOT NULL,
    user_id bigint NOT NULL,
    preference_type character varying(255) NOT NULL,
    preferences jsonb NOT NULL
);


--
-- TOC entry 273 (class 1259 OID 16785)
-- Name: user_preferences_id_seq; Type: SEQUENCE; Schema: migrated_data; Owner: besy
--

ALTER TABLE migrated_data.user_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME migrated_data.user_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 274 (class 1259 OID 16786)
-- Name: vat; Type: TABLE; Schema: migrated_data; Owner: besy
--

CREATE TABLE migrated_data.vat (
    value numeric(2,0) NOT NULL,
    description character varying(255) DEFAULT ''::character varying NOT NULL
);


--
-- TOC entry 3474 (class 2606 OID 16884)
-- Name: address address_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id);


--
-- TOC entry 3476 (class 2606 OID 16886)
-- Name: approvals approvals_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.approvals
    ADD CONSTRAINT approvals_pkey PRIMARY KEY (order_id);


--
-- TOC entry 3478 (class 2606 OID 16888)
-- Name: cost_center cost_center_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.cost_center
    ADD CONSTRAINT cost_center_pkey PRIMARY KEY (id);


--
-- TOC entry 3480 (class 2606 OID 16890)
-- Name: currency currency_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.currency
    ADD CONSTRAINT currency_pkey PRIMARY KEY (code);


--
-- TOC entry 3482 (class 2606 OID 16892)
-- Name: customer_id customer_id_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.customer_id
    ADD CONSTRAINT customer_id_pkey PRIMARY KEY (customer_id, supplier_id);


--
-- TOC entry 3484 (class 2606 OID 16894)
-- Name: invoice invoice_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.invoice
    ADD CONSTRAINT invoice_pkey PRIMARY KEY (id);


--
-- TOC entry 3486 (class 2606 OID 16896)
-- Name: item item_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.item
    ADD CONSTRAINT item_pkey PRIMARY KEY (item_id, order_id);


--
-- TOC entry 3488 (class 2606 OID 16898)
-- Name: order order_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_pkey PRIMARY KEY (id);


--
-- TOC entry 3490 (class 2606 OID 16900)
-- Name: order_status_history order_status_history_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.order_status_history
    ADD CONSTRAINT order_status_history_pkey PRIMARY KEY (id);


--
-- TOC entry 3492 (class 2606 OID 16902)
-- Name: person person_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- TOC entry 3494 (class 2606 OID 16904)
-- Name: quotation quotation_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.quotation
    ADD CONSTRAINT quotation_pkey PRIMARY KEY (order_id, index);


--
-- TOC entry 3496 (class 2606 OID 16906)
-- Name: supplier supplier_name_unique; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.supplier
    ADD CONSTRAINT supplier_name_unique UNIQUE (name);


--
-- TOC entry 3498 (class 2606 OID 16908)
-- Name: supplier supplier_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.supplier
    ADD CONSTRAINT supplier_pkey PRIMARY KEY (id);


--
-- TOC entry 3500 (class 2606 OID 16910)
-- Name: user uk_user_email; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."user"
    ADD CONSTRAINT uk_user_email UNIQUE (email);


--
-- TOC entry 3503 (class 2606 OID 17394)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- TOC entry 3505 (class 2606 OID 16914)
-- Name: user_preferences user_preferences_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (id);


--
-- TOC entry 3507 (class 2606 OID 16916)
-- Name: vat vat_pkey; Type: CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.vat
    ADD CONSTRAINT vat_pkey PRIMARY KEY (value);


--
-- TOC entry 3501 (class 1259 OID 16954)
-- Name: uk_user_keycloak_uuid; Type: INDEX; Schema: migrated_data; Owner: besy
--

CREATE UNIQUE INDEX uk_user_keycloak_uuid ON migrated_data."user" USING btree (keycloak_uuid) WHERE (keycloak_uuid IS NOT NULL);


--
-- TOC entry 3508 (class 2606 OID 17130)
-- Name: approvals approvals_order_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.approvals
    ADD CONSTRAINT approvals_order_id_fkey FOREIGN KEY (order_id) REFERENCES migrated_data."order"(id) ON DELETE CASCADE;


--
-- TOC entry 3509 (class 2606 OID 17135)
-- Name: customer_id customer_id_supplier_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.customer_id
    ADD CONSTRAINT customer_id_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES migrated_data.supplier(id) ON DELETE CASCADE;


--
-- TOC entry 3514 (class 2606 OID 17245)
-- Name: order fkd5whoe5rx0p723swdc3wk4ymh; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT fkd5whoe5rx0p723swdc3wk4ymh FOREIGN KEY (customer_id, supplier_id) REFERENCES migrated_data.customer_id(customer_id, supplier_id);


--
-- TOC entry 3510 (class 2606 OID 17140)
-- Name: invoice invoice_cost_center_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.invoice
    ADD CONSTRAINT invoice_cost_center_id_fkey FOREIGN KEY (cost_center_id) REFERENCES migrated_data.cost_center(id);


--
-- TOC entry 3511 (class 2606 OID 17145)
-- Name: invoice invoice_order_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.invoice
    ADD CONSTRAINT invoice_order_id_fkey FOREIGN KEY (order_id) REFERENCES migrated_data."order"(id);


--
-- TOC entry 3512 (class 2606 OID 17150)
-- Name: item item_order_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.item
    ADD CONSTRAINT item_order_id_fkey FOREIGN KEY (order_id) REFERENCES migrated_data."order"(id) ON DELETE CASCADE;


--
-- TOC entry 3513 (class 2606 OID 17155)
-- Name: item item_vat_value_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.item
    ADD CONSTRAINT item_vat_value_fkey FOREIGN KEY (vat_value) REFERENCES migrated_data.vat(value);


--
-- TOC entry 3515 (class 2606 OID 17160)
-- Name: order order_currency_short_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_currency_short_fkey FOREIGN KEY (currency_short) REFERENCES migrated_data.currency(code);


--
-- TOC entry 3516 (class 2606 OID 17165)
-- Name: order order_delivery_address_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_delivery_address_id_fkey FOREIGN KEY (delivery_address_id) REFERENCES migrated_data.address(id);


--
-- TOC entry 3517 (class 2606 OID 17170)
-- Name: order order_delivery_person_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_delivery_person_id_fkey FOREIGN KEY (delivery_person_id) REFERENCES migrated_data.person(id);


--
-- TOC entry 3518 (class 2606 OID 17175)
-- Name: order order_invoice_address_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_invoice_address_id_fkey FOREIGN KEY (invoice_address_id) REFERENCES migrated_data.address(id);


--
-- TOC entry 3519 (class 2606 OID 17180)
-- Name: order order_invoice_person_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_invoice_person_id_fkey FOREIGN KEY (invoice_person_id) REFERENCES migrated_data.person(id);


--
-- TOC entry 3520 (class 2606 OID 17401)
-- Name: order order_owner_user_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES migrated_data."user"(id);


--
-- TOC entry 3521 (class 2606 OID 17190)
-- Name: order order_primary_cost_center_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_primary_cost_center_id_fkey FOREIGN KEY (primary_cost_center_id) REFERENCES migrated_data.cost_center(id);


--
-- TOC entry 3522 (class 2606 OID 17195)
-- Name: order order_queries_person_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_queries_person_id_fkey FOREIGN KEY (queries_person_id) REFERENCES migrated_data.person(id);


--
-- TOC entry 3523 (class 2606 OID 17200)
-- Name: order order_secondary_cost_center_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_secondary_cost_center_id_fkey FOREIGN KEY (secondary_cost_center_id) REFERENCES migrated_data.cost_center(id);


--
-- TOC entry 3525 (class 2606 OID 17205)
-- Name: order_status_history order_status_history_order_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.order_status_history
    ADD CONSTRAINT order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES migrated_data."order"(id) ON DELETE CASCADE;


--
-- TOC entry 3524 (class 2606 OID 17210)
-- Name: order order_supplier_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data."order"
    ADD CONSTRAINT order_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES migrated_data.supplier(id);


--
-- TOC entry 3526 (class 2606 OID 17215)
-- Name: person person_address_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.person
    ADD CONSTRAINT person_address_id_fkey FOREIGN KEY (address_id) REFERENCES migrated_data.address(id);


--
-- TOC entry 3527 (class 2606 OID 17220)
-- Name: quotation quotation_order_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.quotation
    ADD CONSTRAINT quotation_order_id_fkey FOREIGN KEY (order_id) REFERENCES migrated_data."order"(id) ON DELETE CASCADE;


--
-- TOC entry 3528 (class 2606 OID 17225)
-- Name: supplier supplier_address_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.supplier
    ADD CONSTRAINT supplier_address_id_fkey FOREIGN KEY (address_id) REFERENCES migrated_data.address(id);


--
-- TOC entry 3529 (class 2606 OID 17415)
-- Name: user_preferences user_preferences_user_id_fkey; Type: FK CONSTRAINT; Schema: migrated_data; Owner: besy
--

ALTER TABLE ONLY migrated_data.user_preferences
    ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES migrated_data."user"(id) ON DELETE CASCADE;


-- Completed on 2026-08-09 22:58:06 UTC

--
-- PostgreSQL database dump complete
--
